exclude: ".git|k8s|helmfile|.conf|Dockerfile|migrations|docker-compose-PRODUCTION.yaml|.md|.ico|alembic"
default_stages: [pre-commit, pre-push]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: check-toml
      - id: check-merge-conflict
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3.13
        args: ["--line-length", "80"]
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=80
        additional_dependencies:
          - flake8-bugbear
          - flake8-simplify
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: ty
        name: python type checking
        language: python
        entry: docker
        args:
          [
            "exec",
            "treadmilltracker-backend", "bash", "-c", '"./bin/ty.sh"'
          ]
  - repo: local
    hooks:
      - id: eslint
        name: run eslint
        language: python
        entry: docker
        args:
          [
            "exec",
            "treadmilltracker-frontend", "sh", "-c", '"./bin/eslint.sh"'
          ]